services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      N8N_EDITOR_BASE_URL: '${SERVICE_FQDN_N8N}'
      WEBHOOK_URL: '${SERVICE_FQDN_N8N}'
      N8N_HOST: '${SERVICE_URL_N8N}'
      GENERIC_TIMEZONE: '${GENERIC_TIMEZONE:-Europe/Berlin}'
      TZ: '${TZ:-Europe/Berlin}'
      SERVICE_URL_N8N: '${SERVICE_URL_N8N}'
      COOLIFY_RESOURCE_UUID: lkwg4os8so8c0c4ss40k0sgk
      COOLIFY_CONTAINER_NAME: n8n-lkwg4os8so8c0c4ss40k0sgk
      COOLIFY_URL: 'https://n8n.apperture.mx'
      COOLIFY_FQDN: n8n.apperture.mx
    volumes:
      - 'lkwg4os8so8c0c4ss40k0sgk_n8n-data:/home/node/.n8n'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10
    container_name: n8n-lkwg4os8so8c0c4ss40k0sgk
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.name=n8n-lkwg4os8so8c0c4ss40k0sgk
      - coolify.resourceName=n8n-lkwg4os8so8c0c4ss40k0sgk
      - coolify.projectName=n8n
      - coolify.serviceName=n8n
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - coolify.service.subId=4
      - coolify.service.subType=application
      - coolify.service.subName=n8n
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-lkwg4os8so8c0c4ss40k0sgk-n8n.entryPoints=http
      - traefik.http.routers.http-0-lkwg4os8so8c0c4ss40k0sgk-n8n.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-lkwg4os8so8c0c4ss40k0sgk-n8n.rule=Host(`n8n.apperture.mx`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-lkwg4os8so8c0c4ss40k0sgk-n8n.service=http-0-lkwg4os8so8c0c4ss40k0sgk-n8n
      - traefik.http.routers.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.entryPoints=https
      - traefik.http.routers.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.middlewares=gzip
      - 'traefik.http.routers.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.rule=Host(`n8n.apperture.mx`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.service=https-0-lkwg4os8so8c0c4ss40k0sgk-n8n
      - traefik.http.routers.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.tls=true
      - traefik.http.services.http-0-lkwg4os8so8c0c4ss40k0sgk-n8n.loadbalancer.server.port=1212
      - traefik.http.services.https-0-lkwg4os8so8c0c4ss40k0sgk-n8n.loadbalancer.server.port=1212
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 1212}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://n8n.apperture.mx'
      - caddy_ingress_network=lkwg4os8so8c0c4ss40k0sgk
    networks:
      lkwg4os8so8c0c4ss40k0sgk: null
volumes:
  lkwg4os8so8c0c4ss40k0sgk_n8n-data:
    name: lkwg4os8so8c0c4ss40k0sgk_n8n-data
networks:
  lkwg4os8so8c0c4ss40k0sgk:
    name: lkwg4os8so8c0c4ss40k0sgk
    external: true
configs: {  }
secrets: {  }
